### ISSUE TITLE
_itemname

### ISSUE THREAD

**Issue by snajdan** [RyanTT/DynamicMarket#1]
2015/03/19,  0:31:10 Error in expression <ntSold = _x select 2;
if (_curItemName==_itemName) then {
DYNMARKET_Items_Curren>
2015/03/19,  0:31:10   Error position: <_itemName) then {
DYNMARKET_Items_Curren>
2015/03/19,  0:31:10   Error Undefined variable in expression: _itemname
2015/03/19,  0:31:10 File life_server\Functions\DynMarket\fn_changePrice.sqf, line 22

**Comment by RyanTT** [comment]
Was fixed with the latest Push.
