### ISSUE TITLE
fn_update.sqf Error

### ISSUE THREAD

**Issue by snajdan** [RyanTT/DynamicMarket#2]
2015/03/19,  0:27:56 "Cleanup.sqf gestartet"
2015/03/19,  0:27:56 "########################## DYNAMIC MARKET ##########################"
2015/03/19,  0:27:56 "### >> SUCCESSFULLY LOADED PRICES FROM DATABASE!                 ###"
2015/03/19,  0:27:56 "####################################################################"
2015/03/19,  0:30:01 Error in expression <ect 1;

switch (_mode) do {
case 0:
{
[[DYNAMICMARKET_boughtItems],"TON_fnc_getU>
2015/03/19,  0:30:01   Error position: <DYNAMICMARKET_boughtItems],"TON_fnc_getU>
2015/03/19,  0:30:01   Error Undefined variable in expression: dynamicmarket_boughtitems
2015/03/19,  0:30:01 File mpmissions\KBS_Altis_Life_dynmarket.Altis\core\DynMarket\fn_update.sqf, line 18

**Comment by chris579** [comment]
Just add 
dynamicmarket_boughtitems = []; 

to your confconfiguration.sqf

**Comment by RyanTT** [comment]
Bug has been fixed witht the latest Push.
